"""Validated contracts for claim generation and paper-evidence verification."""

from __future__ import annotations

from html import unescape

from pydantic import BaseModel, ConfigDict, Field, field_validator


class _Evidence(BaseModel):
    model_config = ConfigDict(strict=True, extra="forbid")

    source: int = Field(ge=1)
    quote: str = Field(min_length=1)


class _Claim(BaseModel):
    model_config = ConfigDict(strict=True, extra="forbid")

    text: str = Field(min_length=1)
    evidence: list[_Evidence] = Field(default_factory=list)

    @field_validator("text")
    @classmethod
    def validate_text(cls, value: str) -> str:
        value = value.strip()
        if not value or "\n" in value or "\r" in value:
            raise ValueError("Each claim must be a nonempty single-line block")
        if "citation:" in unescape(value).replace("\\", "").lower():
            raise ValueError("Citation links must be generated by the application")
        return value


class _Draft(BaseModel):
    model_config = ConfigDict(strict=True, extra="forbid")

    claims: list[_Claim] = Field(min_length=1)
    confidence: float = Field(ge=0, le=1)


class _Verdict(BaseModel):
    model_config = ConfigDict(strict=True, extra="forbid")

    candidate: int = Field(ge=1)
    supported: bool


class _Verification(BaseModel):
    model_config = ConfigDict(strict=True, extra="forbid")

    verdicts: list[_Verdict]